
-- Creacion tablespace.
CREATE TABLESPACE XADM_TUTELAS
   DATAFILE 'DF_XADM_TUTELAS.DBF' SIZE 200M 
   ONLINE;
   
--Vemos si fue creado. 
SELECT * FROM DBA_DATA_FILES;

-- Creamos los roles para el desarrollo y mantenimiento.
CREATE ROLE ADMINISTRADOR_BD;

-- Damos permisos para la gestion de las bd.
GRANT CREATE SESSION TO ADMINISTRADOR_BD;
GRANT CREATE ANY TABLE TO ADMINISTRADOR_BD;
GRANT CREATE ROLE TO ADMINISTRADOR_BD;
GRANT CREATE USER TO ADMINISTRADOR_BD;
GRANT CREATE VIEW TO ADMINISTRADOR_BD;
GRANT CREATE ANY INDEX TO ADMINISTRADOR_BD;
GRANT CREATE ANY TRIGGER TO ADMINISTRADOR_BD;
GRANT CREATE ANY PROCEDURE TO ADMINISTRADOR_BD;
GRANT CREATE ANY SEQUENCE TO ADMINISTRADOR_BD;

-- Creamos el usuario
CREATE USER DESARROLLADOR_BD IDENTIFIED BY DESARROLLADOR_BD DEFAULT TABLESPACE XADM_TUTELAS;

-- Damos permisos al usuario sobre el tablespace.
GRANT UNLIMITED TABLESPACE TO DESARROLLADOR_BD;

--Asignamos el rol al usuario
GRANT ADMINISTRADOR_BD TO DESARROLLADOR_BD;